#' table UI Function
#'
#' @description A shiny Module.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#'
#' @noRd
#'
#' @importFrom shiny NS tagList

`%>%` <- dplyr::`%>%`

addResourcePath("d", "inst/app/www/")

mod_table_ui <- function(id, name){
    ns <- NS(id)


    tagList(
      tabsetPanel(
        tabPanel("Table",
                 DT::dataTableOutput(ns('text1')  )
        ),
        tabPanel("Info",

                 HTML('<br>

                      <p> This app involves parsing and filtering multiple output files generated by the  <a href="https://github.com/smithlabcode/preseq">preseq</a>
                      lc_extrap program. This process includes systematically breaking down the files
                      contents to extract relevant information, such as sequencing read counts and
                      library complexities. By applying filters, we can refine the parsed data and
                      focus on the most meaningful insights. This analysis can be performed on each
                      file individually or collectively to enable comparisons and identify trends
                      across different samples or experimental conditions.


                      </p>')
        )



      )
    )
}




# Module Server

#' @rdname mod_table
#' @export
#' @keywords internal

mod_table_server <- function(input, output, session, file){  #,batches,sim){
  ns <- session$ns



  output$text1 <- DT::renderDataTable({


    # if (is.null(dat())) return()
    req(file$goButton())
    res<-file$df()$dat

    rrr<<-res
    #rrr<-as.data.frame(lapply(rrr, unlist))
    #res<-apply(res,2,as.character)
    res<-unname(res)

    res<-as.data.frame(res)
    rrr1<<-res
    colnames(res)<-c("id","TOTAL_READS","EXPECTED_DISTINCT","LOWER_0.95CI","UPPER_0.95CI")
    res<-apply(res,2,as.character)

    if (length(file$df()$inFilename)==1){
    res<-t(res)
      }else{
    res<-res %>% tibble::as.tibble() %>%
      type.convert(as.is = TRUE)
}
    rrrr2<<-res
    #isolate({

      DT::datatable( res,editable = TRUE,selection = 'none',
                     extensions = 'Buttons',rownames=FALSE, options = list(
                       lengthMenu = c(50, 100, 200,2000), pageLength = 1000,
                       dom = 'Blfrtip',
                       scrollX='400px',
                       buttons = list(

                         list(extend = 'excel', title = NULL)#,

                       )


                     )
      )

  #  })

  })







}
## To be copied in the UI
# mod_table_ui("table_1")

## To be copied in the server
# mod_table_server("table_1")
